### ISSUE TITLE
Add suport to version FBSDKCoreKit 9.1.0

### ISSUE THREAD

**Issue by perez-danilo** [saadfarhan124/flutter_facebook_sdk#1]
Hi,

can generate a version for the new FBSDKCoreKit?
I am tryind to do this, and i will test.

s.dependency 'FBSDKCoreKit', '~> 9.1.0'

Thanks

**Comment by perez-danilo** [comment]
#

**Comment by perez-danilo** [comment]
#2 
I think this could help!

**Comment by saadfarhan124** [comment]
fixed in #2
