### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FBSDKCoreKit"

### ISSUE THREAD

**Issue by MuraliThangavel** [saadfarhan124/flutter_facebook_sdk#17]
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 4.3.0, which depends on
      FBSDKCoreKit (~> 13)

    flutter_facebook_sdk (from `.symlinks/plugins/flutter_facebook_sdk/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 9.1.0)

**Comment by abdullahtas0** [comment]
hey! How to solve this problem?

**Comment by Aina27** [comment]
refer to this solution : https://github.com/oddbit/flutter_facebook_app_events/issues/274

**Comment by griajobag** [comment]
flutter_facebook_sdk seems not updated for years. Perhaps the owner of the project is retired already as SE. 

I just faced this situation 
```

Validation failed (409)
Invalid Executable. The executable 'Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' contains bitcode. (ID: XX)

Validation failed (409)
Invalid Executable. The executable 'Runner.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics' contains bitcode. (ID: XX)
```

- Xcode 16
- Flutter 3.27.0

Please use my repository like below in your pubspec.yml : 
```

flutter_facebook_sdk:
    git:
      url: https://github.com/griajobag/flutter_facebook_sdk
      ref: eea9406f32c7b5a1c0ecb441aa81cf5ce86ade98
```

I forked the original source and do some updates. 

Edit : 

This update already contains : 
`- 'FBSDKCoreKit', '~> 16.0.0'`
