### ISSUE TITLE
'onNewIntent' overrides nothing, Class 'FlutterFacebookSdkPlugin' is not abstract and does not implement abstract member public abstract fun onNewIntent(p0: Intent): Boolean defined in io.flutter.plugin.common.PluginRegistry.NewIntentListener

### ISSUE THREAD

**Issue by tvqphong001** [saadfarhan124/flutter_facebook_sdk#22]
Need update kotlin version 1.3.50 -> 1.6.10 
remove ? (Intent?) -> Intent
My code handled exception:
```
    override fun onNewIntent(intent: Intent): Boolean {
        try {
            // some code
            deepLinkUrl = AppLinks.getTargetUrl(intent).toString()
            eventSink!!.success(deepLinkUrl)
        } catch (e: NullPointerException) {
            // handler
            return false
        }
        return false
    }
```

**Comment by ahmad-younis88** [comment]
thanks man , 
its working fine now

**Comment by chiangandy** [comment]
I am using this package and meet this issue right now. according to above conversion sound's like issue can be solve. Could you please describe more detail how to solve this. Thanks a lot.

**Comment by chiangandy** [comment]
> I am using this package and meet this issue right now. according to above conversion sound's like issue can be solve. Could you please describe more detail how to solve this. Thanks a lot.

I solve it. let me explain more detail.
plugin file locate in ...
~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_sdk-1.0.0/android/src/main/kotlin/saad/farhan/flutter_facebook_sdk/FlutterFacebookSdkPlugin.kt

and find the code block and replace it then fix.

Thanks a lot.
