### ISSUE TITLE
Migration to null safety

### ISSUE THREAD

**Issue by WalidChebaro** [saadfarhan124/flutter_facebook_sdk#3]

**Comment by saadfarhan124** [comment]
Hi @WalidChebaro 

flutter_facebook_sdk 1.0.0 is released with support for null safety. You can check [the official pub page(https://pub.dev/packages/flutter_facebook_sdk) and give it a thumbs up if you can thanks !!

**Comment by saadfarhan124** [comment]
Hi @WalidChebaro

flutter_facebook_sdk 1.0.0 is released with support for null safety. You can check [the official pub page](https://pub.dev/packages/flutter_facebook_sdk) and give it a thumbs up if you can thanks !!

**Comment by sadfarhan124** [comment]
Closing the issue now. Let me know if you need anything else. Thanks
