### ISSUE TITLE
invokeMethod("setAdvertiserTracking"... can return nil

### ISSUE THREAD

**Issue by hermanccw** [saadfarhan124/flutter_facebook_sdk#5]
When calling `setAdvertiserTracking`, it can return `nil` according to this line: https://github.com/saadfarhan124/flutter_facebook_sdk/blob/master/ios/Classes/SwiftFlutterFacebookSdkPlugin.swift#L277

However, on the dart side, the code expect a boolean: https://github.com/saadfarhan124/flutter_facebook_sdk/blob/master/lib/flutter_facebook_sdk.dart#L198

**Comment by vishwarajanand** [comment]
https://github.com/saadfarhan124/flutter_facebook_sdk/pull/6
